server:
  port: 8081

spring:
  redis:
    database: 2
    host: 10.0.41.145
    port: 6379
    password: poembro
    lettuce:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1ms
    connect-timeout: 30000ms
  datasource:
    url: jdbc:mysql://10.0.41.145:3306/openresty_china?useSSL=false&autoReconnect=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: poembro

token :  # 加密密钥 NOjyVFBqlCvhWM
  secretKey: abcdefghijklmnopqrstuvwxyz
  expireTime: 3600   # token有效时长

mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    log-level: trace
  mapper-locations: classpath:mapper/*.xml


knife4j:
  enable: true
  setting:
    # default lang
    language: en-US
    # footer
    enableFooter: false
    enableFooterCustom: true
    footerCustomContent: MIT | [Java 全栈](https://pdai.tech)
    # models
    enableSwaggerModels: true
    swaggerModelName: My Models
